### ISSUE TITLE
Missing mixer name in pipeline reported to wrong path

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#11]
In [this config](https://github.com/HEnquist/pycamilladsp-plot/files/6490020/missing-mixer.yml.zip), the use of a missing mixer is reported to `pipeline/0` instead of `pipeline/0/name`.

**Comment by HEnquist** [comment]
Yes that should definitely be on pipeline/0/name. I also notice that there is an earlier check missing, the name can't be an empty string. I'll fix tomorrow. Then (mostly a note to myself so I don't forget) I'll also fix another bug, that target_level should be allowed to be 0, since 0 means it will use the chunksize value instead.

**Comment by HEnquist** [comment]
Can you try it now?

**Comment by JWahle** [comment]
Works for me :+1:
